Copy File To Clipboard After Converting
Tichau/FileConverter pull request #348
Opened 2023-12-04 18:50 UTC by hsayed21

2024-01-19 10:26 UTC, Tichau requested changes
Thanks for you contribution! tell me if you don't have time to make modifications I'll do it.

2024-01-19 10:26 UTC, Tichau commented on Application/FileConverter/ConversionJobs/ConversionJob.cs
These modifications can be discarded since there is no uses of the new using

2024-01-19 10:26 UTC, Tichau commented on Application/FileConverter/Services/ConversionService.cs
> +            ISettingsService settingsService = SimpleIoc.Default.GetInstance<ISettingsService>();
I made some changes removing deprecated dependencies. You can now use `this.settingsService` to access the settings.

2024-01-19 10:26 UTC, Tichau commented on Application/FileConverter/Settings.cs
> +        public bool CheckCopyFilesAfterConverting
I'd prefer the naming 'CopyFilesInClipboardAfterConversion' to be more explicit.

2024-01-19 10:26 UTC, Tichau commented on Application/FileConverter/Settings.cs
> +                this.RaisePropertyChanged();
I made some changes removing deprecated dependencies. You can now use NotifyPropertyChanged instead of RaisePropertyChanged.

2024-01-20 09:45 UTC, hsayed21 commented
Changes done

2024-01-20 12:33 UTC, Tichau commented
Thanks for your reactivity !

2024-01-20 12:33 UTC, merged